# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 568b1c54d069efc30f15bc051f9638fdbe4de9802c1bc18d755bc6631ad8fc3396e152c4fb881e96be935a4dd3c3ae3d2ae8523491f06c0c33fe02b08cc5c2bc

test:
  secret_key_base: e232358f26f290dd60850a9aa73ac3f4e885a9bf3319f096f657f2492f5159183c8a3a0abd6bb75a0c9e52f91c2a920cab4e62ed0e3f791054da00c5cda65ff9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
